### ISSUE TITLE
Make sure the the backend is properly issuing new access tokens

### ISSUE THREAD

**Issue by douglasnaphas** [cdk-turnkey/brian-liberation#14]
Make sure the the backend is properly issuing new access tokens, using the refresh token, when the access token received in cookies is expired.

This is related to https://github.com/douglasnaphas/madliberation/issues/331.

**Comment by douglasnaphas** [comment]
# Test cases
## Test Case 1: Creating a room code
1. Log in as any user.
2. Wait long enough so that the access token received is expired. Confirm that the access token is expired after the waiting period by noting the expiration period in the source code and in the AWS resources, and by noting the JWT claims related to expiry.
3. Attempt to create a room code.
**Expected result**: A room code is created.

## Test Case 2: Joining a sesh
1. As User 1, create a sesh without logging in.
2. As User 2, log in as any user.
3. User 2: Join the sesh created in Step 1.
**Expected result**: User 2 joins the sesh successfully.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Add some logging, like _expired access token found_, _issuing new access token with the refresh token_, or _new access token fetched_.
- [ ] Run through Test Case 1, posting screenshots of the current behavior.
- [ ] Run through Test Case 2, posting screenshots of the current behavior.
- [ ] Implement the fix.
- [ ] Re-run Test Case 1.
- [ ] Re-run Test Case 2.
- [ ] Port the change to Mad Liberation.

**Comment by douglasnaphas** [comment]
I might want to handle https://github.com/douglasnaphas/madliberation/issues/253 (make my signout a real signout), in Mad Liberation and here, before proceeding with this.

It's annoying how people who have clicked "sign out" will (probably, haven't verified) still send JWTs with every request. It means that I can't just detect a token on the backend and start acting on it.
